### ISSUE TITLE
Help launch

### ISSUE THREAD

**Issue by ghost** [xTACTIXzZ/Hydrazine#5]
Hey i would like to run a test with the cflood module but i don't understand how it works

java -jar Hydrazine.jar -h x.x.x.x -p 25565 -m chat -gu random -m cflood

**Comment by stenocyb** [comment]
Hey, in order to make cflood work you have to remove the '-m chat' part of your command. Switches (like -m) can only be used once in the whole command ;) It should look like this in some way:
`java -jar Hydrazine.jar -h x.x.x.x -p 25565 -m cflood -gu random`

This will run the cflood module with the default configuration. (5 bots, 1000ms join interval)
If you would like to change these settings, append the '-c' switch to your command:
`java -jar Hydrazine.jar -h x.x.x.x -p 25565 -m cflood -gu random -c`

**Comment by ghost** [comment]
Ok I will test and how to use the socks proxies? thx

**Comment by stenocyb** [comment]
You can only use one socks proxy for the moment, which you can specify by appending the '-sp' switch:
`java -jar Hydrazine.jar -m cflood -gu random -h x.x.x.x -p 25565 -sp <host:port>`

**Comment by AurelienGamings** [comment]
I get this error + Disconnected client: java.net.SocketException: Connection refused: x.x.x.x

I can't use a file directly?

java -jar Hydrazine1.12.1.jar -h ip.gamingscloud.eu -m cflood -gu random -p 25585 -sp proxy.txt?

**Comment by ghost** [comment]
I get this error + Disconnected client: java.net.SocketException: Connection refused: x.x.x.x

I can't use a file directly?

java -jar Hydrazine1.12.1.jar -h x.x.x.x -m cflood -gu random -p 25585 -sp proxy.txt?

**Comment by stenocyb** [comment]
No you can't use a file directly. It seems to work for me, check if you are using a socks 5 proxy that is working

**Comment by stenocyb** [comment]
You could also setup & run tor as a service and then route the traffic through it. In this case the '-sp' switch argument needs to be 127.0.0.1:9050

**Comment by stenocyb** [comment]
You can now use a file containing proxies directly if you wish. (-sp file.txt)
